version: '3.9'
services:
  db:
    image: postgres:15   
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: rui0421
      POSTGRES_PASSWORD: Higashi0421 
      POSTGRES_DB: rank2-forum
    ports:
      - "5433:5432"               
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
